apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: api-deploy
spec:
  params:
    - name: HUB_REPO
    - name: REVISION
    - name: API_IMAGE
    - name: DB_MIGRATION_IMAGE
    - name: TAG
    - name: HUB_NAMESPACE
    - name: K8S_VARIANT
  workspaces:
    - name: shared-workspace
    - name: kubeconfig-dir
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.HUB_REPO)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.REVISION)
    - name: unit-test
      taskRef:
        name: golang-db-test
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: package
          value: github.com/tektoncd/hub
        - name: packages
          value: ./pkg/...
        - name: path_context
          value: api
        - name: flags
          value: "-p 1 -v --timeout 10m"
      runAfter:
        - fetch-repository
    - name: build-push-api-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.API_IMAGE):$(params.TAG)
        - name: CONTEXT
          value: "api"
        - name: FORMAT
          value: "docker"
      runAfter:
        - unit-test
    - name: build-push-migration-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.DB_MIGRATION_IMAGE):$(params.TAG)
        - name: CONTEXT
          value: "api"
        - name: FORMAT
          value: "docker"
        - name: DOCKERFILE
          value: ./db.Dockerfile
      runAfter:
        - unit-test
    - name: check-db-deployment
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl describe deployment db -n "$(params.HUB_NAMESPACE)" >/dev/null 2>/dev/null
            if [[ $? -eq 0 ]]; then
              printf yes | tee /tekton/results/output-result
            else
              printf no | tee /tekton/results/output-result
            fi
      runAfter:
        - build-push-migration-image
        - build-push-api-image
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: create-db-deployment
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
      params:
        - name: script
          value: |
            kubectl -n $(params.HUB_NAMESPACE) apply -f config/00-init/02-db-pvc.yaml
            kubectl -n $(params.HUB_NAMESPACE) apply -f config/00-init/03-db-deployment.yaml
            kubectl -n $(params.HUB_NAMESPACE) apply -f config/00-init/04-db-service.yaml
      runAfter:
        - check-db-deployment
      when:
        - input: "$(tasks.check-db-deployment.results.output-result)"
          operator: in
          values: ["no"]
    - name: create-new-migration-job
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl delete job db-migration --ignore-not-found
            kubectl apply -n $(params.HUB_NAMESPACE) -f <(sed "s@image:.*@image: $(params.DB_MIGRATION_IMAGE):$(params.TAG)@" config/01-db/10-db-migration.yaml)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: shared-workspace
      runAfter:
        - check-db-deployment
    - name: check-api-deployment
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl describe deployment api -n "$(params.HUB_NAMESPACE)" >/dev/null 2>/dev/null
            if [[ $? -eq 0 ]]; then
              printf yes | tee /tekton/results/output-result
            else
              printf no | tee /tekton/results/output-result
            fi
      runAfter:
        - create-new-migration-job
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: patch-api-image
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl patch deployment api --patch='{"spec":{"template":{"spec":{
              "containers":[{
                "name": "api",
                "image": "$(params.API_IMAGE):$(params.TAG)"
              }]
            }}}}' -n $(params.HUB_NAMESPACE)
      when:
        - input: "$(tasks.check-api-deployment.results.output-result)"
          operator: in
          values: ["yes"]
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
      runAfter:
        - check-api-deployment
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
      params:
        - name: script
          value: |
            kubectl -n $(params.HUB_NAMESPACE) apply -f <(sed "s@image:.*@image: $(params.API_IMAGE):$(params.TAG)@" config/02-api/22-api-deployment.yaml)
            kubectl -n $(params.HUB_NAMESPACE) apply -f config/02-api/23-api-service.yaml
            [[ "$(params.K8S_VARIANT)" == "openshift" ]] && \
            kubectl -n $(params.HUB_NAMESPACE) apply -f config/04-openshift/40-api-route.yaml
      when:
        - input: "$(tasks.check-api-deployment.results.output-result)"
          operator: in
          values: ["no"]
